import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import 'react-toastify/dist/ReactToastify.css';
import RootLayouts from '@/components/layout/RootLayout';
import { SessionProvider } from 'next-auth/react';
import NextAuthProvider from '@/components/layout/NextAuthProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <NextAuthProvider>
          <RootLayouts>{children}</RootLayouts>
        </NextAuthProvider>
      </body>
    </html>
  );
}
